name: project_base_libs_pkg
description: A new Flutter project.
version: 1.0.6
homepage: 'https://github.com/YouXianMing/flutter_project_pkg'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  ####################################################
  # Flutter: Android iOS Linux MacOS Web Windows
  ####################################################

  # [dart.dev] SHA-1,SHA-224,SHA-256,SHA-384,SHA-515,SHA-512/224,SHA-512/256,MD5加密工具
  # https://pub.flutter-io.cn/packages/crypto
  crypto: 3.0.2

  # [tools.dart.dev] 文件元数据信息
  # https://pub.dev/packages/mime
  mime: 1.0.2

  # [jakobservices.ch] 消息通知工具
  # https://pub.flutter-io.cn/packages/event_bus
  event_bus: 2.0.0

  # [flutterchina.club] 网络请求
  # https://pub.flutter-io.cn/packages/dio
  dio: 4.0.6

  # [tekartik.com] Lock
  # https://pub.flutter-io.cn/packages/synchronized
  synchronized: 3.0.0+2

  # [filiph.net] 随机英文单词
  # https://pub.flutter-io.cn/packages/english_words
  english_words: 4.0.0

  # [dart.dev] path_provider
  # https://pub.flutter-io.cn/packages/path_provider
  path_provider: 2.0.11

  # [dart.dev] 路径
  # https://pub.flutter-io.cn/packages/path
  path: ^1.8.2

  # 展开缩放组件
  # https://pub.dev/packages/expandable
  expandable: 5.0.1

  # [romainrastel.com] iOS的section herder悬停效果
  # https://pub.flutter-io.cn/packages/flutter_sticky_header
  flutter_sticky_header: 0.6.4

  # [romainrastel.com] 不规则瀑布流
  # https://pub.flutter-io.cn/packages/flutter_staggered_grid_view
  flutter_staggered_grid_view: 0.6.2

  # [flutter.dev] 本地持久化工具
  # https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: 2.0.15

  # [fluttercandies.com] 瀑布流
  # https://pub.flutter-io.cn/packages/waterfall_flow
  waterfall_flow: 3.0.2

  # [getx.site] 状态管理,依赖注入,路由管理等工具合集
  # https://pub.flutter-io.cn/packages/get
  get: 4.6.5

  # 加载动画合集
  # https://pub.flutter-io.cn/packages/loading_animations
  loading_animations: 2.2.0

  # 加载动画合集
  # https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: 5.1.0

  # 加载动画合集
  # https://pub.dev/packages/loading_indicator
  loading_indicator: 3.1.0

  # 加载动画合集
  # https://pub.dev/packages/loading_animation_widget
  loading_animation_widget: ^1.2.0+2

  # [作者退圈了] 上拉加载,下拉刷新,请使用下面的 'pull_to_refresh_flutter3'
  # https://pub.flutter-io.cn/packages/pull_to_refresh
  # pull_to_refresh: 2.0.0

  # 上拉加载,下拉刷新
  # https://pub.flutter-io.cn/packages/pull_to_refresh_flutter3
  pull_to_refresh_flutter3: 2.0.1

dev_dependencies:

  ####################################################
  # Flutter: Android iOS Linux MacOS Web Windows
  ####################################################

  # FLUTTER: Android iOS Linux MacOS Web Windows
  # https://pub.flutter-io.cn/packages/flutter_lints
  flutter_lints: 2.0.1

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
